# Meaning of torch.sum

https://docs.pytorch.org/docs/stable/generated/torch.sum.html#torch.sum

Two params
- dim (int or tuple of ints, optional) – the dimension or dimensions to reduce. If None, all dimensions are reduced.
- keepdim (bool, optional) – whether the output tensor has dim retained or not. Default: False.

dim 的意思就是消灭（reduce） 第 dim 个维度

In [2]:
import torch
M = torch.tensor([
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
])
M.shape

torch.Size([3, 2])

In [5]:
# We can see that the first dim of M is row, if we reduce row, the remaining sum has only 2 values
# and the second dim on M is column, if we reduce column, the remaining sum has 3 values
M.sum(0)

tensor([ 9, 12])

In [17]:
M.sum(1).shape

torch.Size([3])

In [8]:
# How about sum for a 3 dim tensor?
M3 = torch.tensor([[
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
], [
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
], [
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
], [
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
]])
M3.size()

torch.Size([4, 3, 2])

In [9]:
M3.sum(0)

tensor([[ 4,  8],
        [12, 16],
        [20, 24]])

In [10]:
M3.sum(0).size()

torch.Size([3, 2])

In [11]:
M3.sum(1)

tensor([[ 9, 12],
        [ 9, 12],
        [ 9, 12],
        [ 9, 12]])

In [12]:
M3.sum(1).size()

torch.Size([4, 2])

可见，第一个维度是最外层的 [], 第二个维度是第二层的[], 依次类推，dim 指向哪一层就脱哪一层的 [] 非常有趣
可以看到文档里说 dim 可以是 tuple, 不知道 python 的 tuple 是否只能是两个数，问了下豆包，不是，所以dim 使用tuple 的话就是指定哪几层的 []

再来看第二个参数 keepdim, 它是再求和的同时保留这个维度，也就是 [] 不脱，但是求和的这一层维度数量变成了 1

In [13]:
M.sum(0, keepdim=True)

tensor([[ 9, 12]])

In [15]:
M.sum(0, keepdim=False)

tensor([ 9, 12])

In [14]:
M.sum(1, keepdim=True)

tensor([[ 3],
        [ 7],
        [11]])

In [5]:
# Let's see broadcasting rules
M1 = torch.tensor([
    [1, 2],  # 第0行
    [3, 4],  # 第1行
    [5, 6]   # 第2行
])
M2 = torch.tensor([2, 3, 4])
M1 / M2

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1